### ISSUE TITLE
Toggling comments in 'set' commands sections

### ISSUE THREAD

**Issue by hfuentes-jnpr** [codeout/vscode-junos#10]
🟢 Block comments work correctly, but toggling line comments, both Edit Menu & keyboard **Ctrl + /**  insert  a couple of  forward slashes; 🚩 for set commands **#** could be the consistent way for comments.

**Comment by codeout** [comment]
Thanks for pointing that out.

New version v0.2.1 has been published with the line comment fix.
If you still see any problem, please reopen this issue.

**Comment by hfuentes-jnpr** [comment]
Excellent: 
Just tested and works flawlessly
Great contribution!! @codeout
