### ISSUE TITLE
Set snmp name not supported

### ISSUE THREAD

**Issue by Administratoor** [codeout/vscode-junos#11]
The following snippet is highlighted in red:
`set snmp name yourRouterNameHere`

The config runs on different Junos devices.

Are you able to fix it?

**Comment by codeout** [comment]
Thanks for your report. That should be a bug, I'll take a look.

**Comment by codeout** [comment]
I've just published `v0.2.2` with the fix.

![image](https://user-images.githubusercontent.com/921696/137636341-f06df743-41e0-404a-8617-8f769b2d06b1.png)

Please try the latest version and reopen this issue if you see any further problems. Thanks again for your report!
