### ISSUE TITLE
fxp0 interface type is not recognized

### ISSUE THREAD

**Issue by cardinal-cc** [codeout/vscode-junos#12]
fxp0 is not colored at all (though the sub elements like description or address are correctly identified and colored)

this is within (at least) "set interfaces" and "set groups ... interfaces"

```

set interfaces fxp0 description management
set interfaces fxp0 unit 0 family inet address 10.1.1.10/24
set interfaces fxp0 unit 0 inet6 address fc00::00b:10:1:1:10/64
!
set groups re1 interfaces fxp0 unit 0 family inet address 10.1.1.50/24 master-only
set groups re1 interfaces fxp0 unit 0 family inet6 address fc00::00b:10:1:1:50/64 master-only
```

![vscode-issue](https://user-images.githubusercontent.com/30277417/141810259-d30028d3-0bfe-44f2-acf0-19f33fee6ea0.png)

**Comment by codeout** [comment]
Thanks for your report!

Just published `0.2.4` with the fix. Please reopen this issue if you see any further problem.

![image](https://user-images.githubusercontent.com/921696/152668913-0f58e7f3-1b98-48cb-ab35-f3d3f2abd2f3.png)
