### ISSUE TITLE
incorrect highlighting for subinterface with IPv6 address

### ISSUE THREAD

**Issue by cardinal-cc** [codeout/vscode-junos#13]
using a sub-interface with IPv6 address seems to break the delineation between the interface identifier causing misidentification and coloring
_(note that without the IPv6 address specified, the coloring is correct, with the IPv6 address present the incorrect behavior happens)_

```
set interfaces ae0 unit 6 family inet6 description ipv6
set interfaces ae0 unit 6 family inet6 address 
set interfaces ae0 unit 6 family inet6 address fc00:fac1::172:24:71:10/64
```

![vscode-issue](https://user-images.githubusercontent.com/30277417/141810671-58a03fbb-7e80-40c1-b101-0dae0073b14d.png)

**Comment by codeout** [comment]
Thanks for your report!

Just published `0.2.4` with the fix. Please reopen this issue if you see any further problem.

![image](https://user-images.githubusercontent.com/921696/152668952-4926a9d4-1273-43eb-90af-780ea89b0026.png)
