### ISSUE TITLE
Member-range

### ISSUE THREAD

**Issue by hroberts65616** [codeout/vscode-junos#15]
I installed this extension to VSC, and opened one of my juniper config files.
It immediately gave an error for this line:

set interface interface-range SCOPE member-range ge-0/0/0 to ge-0/0/3

It does not like the to ge-0/0/3 at the end.

**Comment by codeout** [comment]
Thanks for your issue report, I'll take a look into this.

**Comment by codeout** [comment]
Hi @hroberts65616, I've just published v0.2.5 with the fix. Please try it and reopen this issue if you see any further problems.

https://user-images.githubusercontent.com/921696/180848963-029ee759-54cf-4b54-9621-1a80b76ef023.mov
