### ISSUE TITLE
auto-complete not working

### ISSUE THREAD

**Issue by terafirmanz** [codeout/vscode-junos#19]
Hi, not sure if this is an extension issue or something on my computer but I can't get auto-completion to work. I am able to for other languages and plugins but not when I have a file set to Junos.

Installed and re-installed the plugin and restarted VSCode.

**Comment by terafirmanz** [comment]
so sorry now realise the config has to be saved to a file then it works.

**Comment by codeout** [comment]
I'm glad to hear that. Yes, we need to save a file to enable auto-completion for some reason 🤔
