### ISSUE TITLE
Jinja comments not working

### ISSUE THREAD

**Issue by jacobw** [codeout/vscode-junos#23]
The closing tag of a Jinja comment doesn't appear to be parsed correctly.

{# ... #}

It looks the second # gets interpreted as a comment, so the trailing } gets ignored, which breaks the encompassing hierarchy.

**Comment by codeout** [comment]
Hi,

Yes, the plugin should parse just like Junos does.
I don't believe we can support both Junos and Jinja syntax as they conflict with each other theoretically.

**Comment by jacobw** [comment]
yeah makes sense. Thanks for the response.
