### ISSUE TITLE
VSCode highlighting valid lines in red (different from previous similar issue)

### ISSUE THREAD

**Issue by Aurux** [codeout/vscode-junos#24]
Any line that enables an interface such as `set interfaces ge-0/0/0 enable` will have the enable keyword underlined in red even though it's a valid command. The same goes for `apply-groups-except`. 
![image](https://github.com/codeout/vscode-junos/assets/38943986/eda012b8-ee18-45a9-9e98-f45a0320cb9d)
![image](https://github.com/codeout/vscode-junos/assets/38943986/a3cec51e-1f14-42ad-b1a3-4f9a1236c51e)

**Comment by codeout** [comment]
Thank you for reporting this issue. I will take a look and get back to you in a few days.

**Comment by codeout** [comment]
Hi, I've just published `v0.3.3` with the fixes. Hoping it works for you.

<img width="513" alt="image" src="https://github.com/codeout/vscode-junos/assets/921696/ab4de501-1950-42b0-b7bd-aeee012c8573">

**Comment by Aurux** [comment]
Yes this works perfectly. Thank you for your work!
