### ISSUE TITLE
"enable" incorrectly highlighted on IRB interfaces.

### ISSUE THREAD

**Issue by Aurux** [codeout/vscode-junos#25]
Apologies for bringing another issue to you so soon! It seems there's now an issue with enable being incorrectly highlighted as invalid on IRB interfaces.

![image](https://github.com/codeout/vscode-junos/assets/38943986/6180f0f5-ff34-4c82-be16-3be17da4a241)

**Comment by codeout** [comment]
Thank you for the issue report, always appreciated!

ref: #24

**Comment by codeout** [comment]
Hi, I've published `v0.3.4` to fix this issue. Please reopen this if you have any further problem.

<img width="678" alt="image" src="https://github.com/codeout/vscode-junos/assets/921696/89142a29-b7e8-49c5-b89c-728ca05e4b47">
