### ISSUE TITLE
If delete is used as the first line of the file, the next line will be highlighted as invalid.

### ISSUE THREAD

**Issue by Aurux** [codeout/vscode-junos#26]
When writing full configuration I put the delete keyword at the top to completely clear the previous config before applying the new one. This seems to cause the first line under delete to always be flagged as invalid.

![image](https://github.com/codeout/vscode-junos/assets/38943986/dff40bb4-e59e-4c71-b170-638bc9b87d93)

**Comment by codeout** [comment]
Hi, I've published `v0.3.4` to fix this issue. Please reopen this if you have any further problem.

<img width="664" alt="image" src="https://github.com/codeout/vscode-junos/assets/921696/89bad143-fd6a-46dd-b73b-0500f8e91462">
