### ISSUE TITLE
Missing option with groups and snmp

### ISSUE THREAD

**Issue by cannotcodetm** [codeout/vscode-junos#30]
Moi,

I noticed two things which appear to be not implemented yet:

- [`groups`](https://www.juniper.net/documentation/us/en/software/junos/cli-reference/topics/ref/statement/groups.html)misses `when` option

- [`snmp`](https://supportportal.juniper.net/s/article/EX-QFX-Understanding-the-SNMP-stats-cache-lifetime-option?language=en_US) misses `stats-cache-lifetime` option

**Comment by codeout** [comment]
Thanks for your report, I will be looking into this.

**Comment by codeout** [comment]
Hi @mrgohin, 

I've published v0.4.0 with the fixes, please try it if you have time.
https://marketplace.visualstudio.com/items?itemName=codeout.vscode-junos

I'm going to close this issue but feel free to re-open if you see any further problems.
Thank you again for the issue report.
