### ISSUE TITLE
set security commands unrecognized

### ISSUE THREAD

**Issue by maximegy** [codeout/vscode-junos#4]
Hi,
Hi have some commands that are unrecognized:
```
set security alg dns disable
set security alg h323 disable
set security alg rtsp disable
set security alg sip disable
set security forwarding-options family inet6 mode packet-based
set security forwarding-options family mpls mode packet-based
set security forwarding-options family iso mode packet-based
```
![Capture d’écran 2019-10-23 à 10 28 03](https://user-images.githubusercontent.com/18288976/67373394-d386f680-f57f-11e9-88a3-dc137bbc9cc0.png)

Can you help ?

**Comment by codeout** [comment]
Sure, I'll take a look. Thanks for your report.

**Comment by codeout** [comment]
Newer version has been released with `set security` syntax support.
Hope it works for you. Enjoy!

![image](https://user-images.githubusercontent.com/921696/68133313-7cabf480-ff63-11e9-8881-d8230f147c4b.png)
