### ISSUE TITLE
set security policies from-zone syntax not recognized

### ISSUE THREAD

**Issue by ArvidSagbrant** [codeout/vscode-junos#5]
![junos](https://user-images.githubusercontent.com/57488388/68388617-61a6d380-0161-11ea-88a1-5ff5749a13d3.png)

**Comment by codeout** [comment]
Thanks for your report, it looks like a bug. I'll take a look.

**Comment by codeout** [comment]
Should be fixed in v0.1.7.

![image](https://user-images.githubusercontent.com/921696/69003825-fa043b80-094b-11ea-8489-8a5116706ce0.png)
